[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
remittance = "72citsVT8pcy5orD5HVAS9UN1aBspCkui1NmcGAB8Xsg"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
